# Generated by Django 5.2.1 on 2025-06-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='carritoitem',
            old_name='carrito_id',
            new_name='carrito',
        ),
        migrations.RenameField(
            model_name='carritoitem',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
