# Generated by Django 5.2.3 on 2025-09-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='banco',
            field=models.CharField(default='Banco Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='cedula',
            field=models.CharField(default='00000000', max_length=12),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='nombre_titular',
            field=models.CharField(default='Nombre Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='numero_cuenta',
            field=models.CharField(default='Cuenta Desconocido', max_length=30),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='telefono',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tipo_cuenta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil')], max_length=20),
        ),
    ]
