# Generated by Django 5.2.3 on 2025-09-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_metodopago_banco_metodopago_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
