# Generated by Django 5.2.3 on 2025-09-25 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_alter_metodopago_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'get_latest_by': 'creado_en', 'ordering': ['creado_en']},
        ),
        migrations.AddField(
            model_name='metodopago',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
