# Generated by Django 5.2.3 on 2025-09-25 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_alter_metodopago_options_metodopago_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=12, validators=[django.core.validators.RegexValidator(message='Este campo solo acepta números', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='numero_cuenta',
            field=models.CharField(default='0000000000', max_length=30, validators=[django.core.validators.RegexValidator(message='Este campo solo acepta números', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='telefono',
            field=models.CharField(default='00000000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Este campo solo acepta números', regex='^\\d+$')]),
        ),
    ]
