# Generated by Django 5.2.3 on 2025-08-20 18:25

import usuarios.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personas',
            managers=[
                ('objects', usuarios.managers.Persona()),
            ],
        ),
        migrations.AddField(
            model_name='personas',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
