# Generated by Django 5.2.3 on 2025-08-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.TextField(),
        ),
    ]
