# Generated by Django 5.2.3 on 2025-07-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_unidades_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='cantidad',
            field=models.IntegerField(max_length=5),
        ),
    ]
