# Generated by Django 5.2.3 on 2025-07-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_unidades_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
