# Generated by Django 5.2.3 on 2025-07-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_unidades_tiempo'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.categorias'),
        ),
    ]
