# Generated by Django 5.2.3 on 2025-08-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='tiempo',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
