# Generated by Django 5.2.3 on 2025-09-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0008_alter_producto_nombre_alter_unidades_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=50),
        ),
    ]
