# Generated by Django 5.2.3 on 2025-09-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0009_alter_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
