# Generated by Django 5.2.3 on 2025-09-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0010_alter_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='tiempo',
            field=models.TextField(max_length=20),
        ),
    ]
